/**
 * accessV2Requirements — the CAPABILITY.ACCESS_V2 requirement list, DERIVED FROM THE DOCUMENTS.
 *
 * The probe exists because one unknown field fails a whole GraphQL document, so an endpoint that
 * has *some* of the v2 schema must read as "absent" rather than half-working. That only holds if
 * the requirement list actually covers what the documents select — and a hand-written list does
 * not: the shipped one named 12 entity types and 13 fields while the documents select ~120 fields
 * across 13 types, omitting `ConfigLintEvent` entirely along with `Subject.isLegacyAdopted`,
 * `SubjectMembership.seededWhilePaused`, `PendingAction.cancelledBy` and many more. A partial
 * publish missing any of those read as CAPABLE and then whole-document-failed the query it broke.
 *
 * So the list is GENERATED by walking the parsed documents. It cannot drift: adding a field to a
 * query adds it to the probe in the same edit.
 *
 * The one thing a GraphQL AST cannot tell us without the schema is which ENTITY a selection set
 * belongs to. `TYPE_OF_FIELD` supplies that — a small dictionary of field name → entity type, and
 * `deriveRequirements` THROWS on any selection set it cannot map, so a new nested selection is a
 * loud failure in the tests rather than a silent hole in the gate.
 */

/**
 * Field name → the entity type its selection set describes. Field names are unambiguous across the
 * v2 documents (`subject` is always a Subject, `config` always a SubjectVouchConfig, and so on).
 */
export const TYPE_OF_FIELD = {
  // roots
  organization: 'Organization',
  membershipAuthorityContract: 'MembershipAuthorityContract',
  subjectMemberships: 'SubjectMembership',
  pendingActions: 'PendingAction',
  subjectVouchRecords: 'SubjectVouchRecord',
  subjectMembershipEvents: 'SubjectMembershipEvent',
  configLintEvents: 'ConfigLintEvent',
  // nested
  membershipAuthority: 'MembershipAuthorityContract',
  authority: 'MembershipAuthorityContract',
  subjects: 'Subject',
  subject: 'Subject',
  voucherSubject: 'Subject',
  managerSubject: 'Subject',
  vouchConfig: 'SubjectVouchConfig',
  config: 'SubjectVouchConfig',
  managerConfig: 'ManagerConfig',
  perms: 'PermRow',
  memberRoles: 'GroupComposition',
  groups: 'GroupComposition',
  rule: 'AccessRule',
  pendingAction: 'PendingAction',
};

/** Introspection answers about entity fields; meta fields are never in `__type.fields`. */
const IGNORED_FIELDS = new Set(['__typename']);

/**
 * Walk parsed documents and collect every `{ type, field }` they select.
 *
 * @param {object[]} documents - parsed GraphQL documents (what `gql` returns)
 * @returns {Array<{type: string, field: string}>} de-duped, stable order
 */
export function deriveRequirements(documents = []) {
  const found = new Map(); // `${type}.${field}` -> requirement
  const unmapped = new Set();

  const visit = (selectionSet, parentType) => {
    for (const sel of selectionSet?.selections || []) {
      if (sel.kind !== 'Field') continue;
      const name = sel.name?.value;
      if (!name || IGNORED_FIELDS.has(name)) continue;

      if (parentType) found.set(`${parentType}.${name}`, { type: parentType, field: name });

      if (sel.selectionSet) {
        const childType = TYPE_OF_FIELD[name];
        if (!childType) {
          unmapped.add(name);
          continue;
        }
        visit(sel.selectionSet, childType);
      }
    }
  };

  for (const doc of documents || []) {
    for (const def of doc?.definitions || []) {
      if (def.kind !== 'OperationDefinition') continue;
      // The operation's own root selections have no parent entity — `organization` is a query
      // field, not a field OF something — so they are only recursed into, never required.
      for (const sel of def.selectionSet?.selections || []) {
        if (sel.kind !== 'Field' || !sel.selectionSet) continue;
        const rootType = TYPE_OF_FIELD[sel.name?.value];
        if (!rootType) {
          unmapped.add(sel.name?.value);
          continue;
        }
        visit(sel.selectionSet, rootType);
      }
    }
  }

  if (unmapped.size > 0) {
    throw new Error(
      `accessV2Requirements: no entity type mapped for selection(s) ${[...unmapped].join(', ')}. `
      + 'Add them to TYPE_OF_FIELD — an unmapped selection would be a silent hole in the '
      + 'CAPABILITY.ACCESS_V2 gate.'
    );
  }

  return [...found.values()];
}
